### ISSUE TITLE
Example can cause a lot of AWS spend

### ISSUE THREAD

**Issue by smcpeck** [terraform-aws-modules/terraform-aws-efs#10]
## Description
_Maybe not really "bug"... but not a feature request either, IMO._ **The example should really be changed a bit given the potential cost implications of running it without scrutiny.**

### Problem:
The current example can quickly chew up some AWS spend...
![image](https://user-images.githubusercontent.com/8724583/215180246-fec97133-ce12-4590-84e9-8ae5cfb24002.png)

### Suggestion:
1. Change the region to "YOUR-REGION" so resources don't end up somewhere that the user might not be monitoring. Region should always be a very conscious choice.
2. Reduce the `provisioned_throughput_in_mibps` from 256 to something very small.
3. Better yet, change the example to Elastic Throughput!

**Comment by bryantbiggs** [comment]
apologies - the examples are intended to show the different configurations a module supports and also to ensure that the different use cases are actually supported and work as intended. In this case, provisioned throughput is shown to ensure users can set and configure that. If we can lower the value, and cost, then please feel free to submit a PR for that
