### ISSUE TITLE
AWS EFS Policy Default

### ISSUE THREAD

**Issue by MaruElbostahi** [terraform-aws-modules/terraform-aws-efs#11]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ x  ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version: 1.3.7

- Provider version(s): 1.1.1

## Reproduction Code [Required]

You have to create an efs with the module and set the "deny_nonsecure_transport = true"
The policy that this will generate will not be right, but it will be incomplete

 no
 yes
 i did it 

## Expected behavior

 I am expecting that the bug will be solved and the wrong policy will be changed with the correct one

## Actual behavior

 I was not able to mount and i got a message "access denied, even if i had all the permission"

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.4.0 :tada:
