### ISSUE TITLE
Add "transition_to_archive" to EFS lifecycle_policy

### ISSUE THREAD

**Issue by ChiaraBissoEng** [terraform-aws-modules/terraform-aws-efs#22]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality:
  https://github.com/hashicorp/terraform-provider-aws/blob/v5.32.0/CHANGELOG.md

## Describe the solution you'd like.
I would like to add and change "transition_to_archive" value of EFS lifecycle_policy, in addition to "transition_to_ia"  and "transition_to_primary_storage_class"

**Comment by antonbabenko** [comment]
Sounds good, PR is welcome

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.6.0 :tada:
