### ISSUE TITLE
publish latest version to Terraform registry

### ISSUE THREAD

**Issue by digorgonzola** [terraform-aws-modules/terraform-aws-efs#25]
## Description

Can you please publish v1.6.0 to the Terraform registry? It's still sitting a v1.4.0...

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by bryantbiggs** [comment]
cc @antonbabenko

**Comment by antonbabenko** [comment]
Fixed
