### ISSUE TITLE
Provisioned throughput cost warning

### ISSUE THREAD

**Issue by kodakmoment** [terraform-aws-modules/terraform-aws-efs#28]
## Is your request related to a problem? Please describe.
I was testing out using EFS as home folder in EC2 and blindly copied the example code thinking EFS is elastic only. The first example uses a 256MiB/s provisioned throughput mode that costs $6/MB/month roughly $50 each day. Obviously this is a user error, but a fair warning would be nice. I was lucky enough to check the cost explorer after a short time.

**Comment by antonbabenko** [comment]
Too bad. Could you please comment on that line in the example code and open a PR?
