### ISSUE TITLE
Backup policy error

### ISSUE THREAD

**Issue by jeenadeepak** [terraform-aws-modules/terraform-aws-efs#4]
## Description
Terraform apply command failed partially when aws backup is not available for any specific region, I have disabled enable_backup_policy but still it is throwing error.

### Terminal Output Screenshot(s)

Error: error putting EFS Backup Policy (fs-0404fe3e214dded87): ValidationException: AWS Backup is not available in this region. For more information, see https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services.

**Comment by bryantbiggs** [comment]
resolved in #5
