### ISSUE TITLE
throughput_mode: elastic not supported

### ISSUE THREAD

**Issue by awscoe** [terraform-aws-modules/terraform-aws-efs#9]
## Description

EFS supports 3 throughput modes: `bursting`, `provisioned`, `elastic`
Please refer: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#throughput_mode

But `terraform-aws-efs` module supports `bursting` and `provisioned` throughput modes only.

When trying to use `elastic` throughout mode getting the following error.

```terraform
module "efs" {
  source = "terraform-aws-modules/efs/aws"
  performance_mode                = "generalPurpose"
  throughput_mode                 = "elastic"
}

│ Error: expected throughput_mode to be one of [bursting provisioned], got elastic
│ 
│   with module.efs.aws_efs_file_system.this[0],
│   on .terraform/modules/efs-csi.efs/main.tf line 14, in resource "aws_efs_file_system" "this":
│   14:   throughput_mode                 = var.throughput_mode
```
Please add the support for `elastic` throughput mode.

**Comment by bryantbiggs** [comment]
the module doesn't limit the `throughput_mode` - it looks like this option was added in [v4.42.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4420-november-28-2022) so you'll just need to ensure you are using at minimum that version of the AWS provider
